services:
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data
  redis_bp:
    image: redis:alpine
    restart: unless-stopped
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
    volumes:
      - redis_volume_bp:/data

volumes:
  psql_volume_bp:
  redis_volume_bp:
